// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LocalFocusTimeTracker
{
    internal sealed partial class Vsix
    {
        public const string Id = "LocalFocusTimeTracker.ba9e48b4-68bc-480c-bd45-c71fedf48b2d";
        public const string Name = "LocalFocusTimeTracker";
        public const string Description = @"Tracks time spent in Visual Studio when active";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "LocalFocusTimeTracker";
        public const string Tags = "";
    }
}
